### ISSUE TITLE
CNY,TWD,HKD currency error occured

### ISSUE THREAD

**Issue by tokipon** [nihaopay/nihaopay-magento2#1]
Our site is required those currecny code CNY,TWD and HKD.
But the following error occurs.
CNY
{"success":false,"error":"Payment failed, please try again later The currency field not valid."}
TWD,HKD
{"success":false,"error":"Payment failed, please try again later Merchant config error"}
JPY is no occured those issue.

Magento ver. 2.2.1
Please check this issue.

**Comment by nihaopay** [comment]
We don't support currency TWD. For HKD, please let me know your merchant ID and Name, we can add config for you. If you have any questions, please email us support@nihaopay.com, Thanks
